### ISSUE TITLE
Trying to get this to work for my Ubuntu Plex Media Server but get the following

### ISSUE THREAD

**Issue by ha77man** [hjaltij/SiriProxy-Plex#5]
I have included the plex config info in the file then run the bundle:

mark@PC-Ha77man:~$ cd SiriProxy
mark@PC-Ha77man:~/SiriProxy$ siriproxy bundle
Updating git://github.com/hjaltij/SiriProxy-Plex.git
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using cora (0.0.3) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using uuidtools (2.1.2) 
Using siriproxy (0.3.0) from source at . 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using siriproxy-plex (0.0.3) from git://github.com/hjaltij/SiriProxy-Plex.git (at master) 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

Then I start the server and get this error....

mark@PC-Ha77man:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for mark: 
Starting SiriProxy on port 443..
/home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:17:in`block in initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`<main>'

**Comment by ha77man** [comment]
This might be more useful?

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001b050d0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001b04ba8>, @zip_stream=#Zlib::Deflate:0x00000001b04b80, @consumed_ace=false, @name="iPhone", @ssled=false>
/home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:1:in `require': cannot load such file -- CGI (LoadError)
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:1:in`<top (required)>'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/siriproxy-plex.rb:24:in `require'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/siriproxy-plex.rb:24:in`<top (required)>'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:22:in `require'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:22:in`block in load_plugins'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:14:in `each'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:14:in`load_plugins'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:8:in `initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:21:in`new'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:21:in `block (2 levels) in initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1432:in`call'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1432:in `event_callback'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /home/mark/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`<main>'

**Comment by rckcrlr** [comment]
Looks like a config.yml problem but not sure.  Did you add lines to your config.yml file including the index variable?  Check the config-info.yml file in the siriproxy-plex source tree root to see an example.

**Comment by ha77man** [comment]
I added it into the config.yml then run the siriproxy bundle in the siri directory. see below my config file

port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

```
- name: 'Example'
  path: './plugins/siriproxy-example'

- name: 'SiriIMDB'
  git: 'git://github.com/parm289/SiriProxy-SiriIMDB.git'

- name: 'Plex'
  git: 'git://github.com/hjaltij/SiriProxy-Plex.git'
  plex_host: '192.168.0.1' #Internal IP address of your Plex Media Server.
  plex_port: '32400' #Most likely you won't have to change this, it runs on port 32400 by default.
  plex_tv_index: '2' #Most likely won't have to change this. This is the path to your TV index within PMS

- name: 'Twitter'
  git: 'git://github.com/netpro2k/SiriProxy-Twitter.git'
  consumer_key: "KMJV3p0GLZozNaWCn2k6tw"
  consumer_secret: "6kv6zA5JGfRzZJ0Yxt7oAOcFAHt06f6KINqU6L3I17I"
  oauth_token: "399968832-JmGt4PUvaP7ZJ244DaWL16r1yaHpddBmVUrVMggf"
  oauth_token_secret: "aNiLFAGIFgqLmRc1wkYiOLoLmkUXjrz6ppHfuOqBhkY"

# - name: 'Thermostat'
#   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
#   host: '192.168.2.71' 

# - name: 'Twitter'
#   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
#   consumer_key: "YOUR_KEY" 
#   consumer_secret: "YOUR_SECRET"
#   oauth_token: "YOUR_TOKEN" 
#   oauth_token_secret: "YOUR_TOKEN_SECRET"

# Note: Eliza should not be run with other plugins
# - name: 'Eliza'
#   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

# Below are not actual plugins, just further example of config options

# - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

# - name: 'AnotherPlugin'
#   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
```
